### ISSUE TITLE
Different img size

### ISSUE THREAD

**Issue by Ahnsun** [pals-ttic/adapting-CLIP#1]
Hi, I noticed that spatial_res50 only support the img size of 224. What should I do about pad when the img size is multi-scale? For example img_size = (608, 1088). Thanks a lot!

**Comment by raymondyeh07** [comment]
Hi @Ahnsun ,

Currently, the input image is resized to 224x244 during pre-processing.
For fully convolutional backbones, we should be able to support variable image size. We will add this support soon.

Raymond

**Comment by raymondyeh07** [comment]
We have added support for using a different image size. However, the quality seems to be better (anecdotally) by resizing to 224x224.
