### ISSUE TITLE
Something wrong in Eq. (7) in the manuscript

### ISSUE THREAD

**Issue by rshaojimmy** [pals-ttic/adapting-CLIP#3]
Hi,

Thanks for your great work!

May I ask if there is something wrong in the first term of Eq. (7) in the manuscript as there are duplicated W<sup>V</sup> without keys (K).

Thanks.

**Comment by raymondyeh07** [comment]
Hi @rshaojimmy,

Thanks for the catch. There is a typo in Eq. (7). 
The first W<sup>V</sup> should be W<sup>K</sup>, as an attention takes in a Query and a Key. 

We will update the arxiv version.

Best,
Raymond

**Comment by rshaojimmy** [comment]
Got it. Thanks!

**Comment by rshaojimmy** [comment]
May I further ask what is the second term in Eq. (7) for? The first term is the self-attention conduced within the region r. Why should add one more second term compared to normal self-attention?

Thanks.

**Comment by raymondyeh07** [comment]
Recall, we defined \mathcal{R} to be a set of patch indices, i.e., it does not contain the region token r<sup>(l)</sup>.
In a normal self-attention, each token also computes an attention with itself. Hence, we needed the second term.

Side Note: We could have defined the set \mathcal{R} to also include the region token then we will only have the first term. However, this requires a single notation for both patch (f) and region token (r), which we thought might confuse the reader.

**Comment by rshaojimmy** [comment]
Thanks! But it seems that this paper did not explicitly mention that \mathcal{R} does not contain the region token r(l) in the manuscript.

**Comment by raymondyeh07** [comment]
In the paper, "\mathcal{R} denotes a set of patch indices covered by the region". 
As a region token does not correspond to a patch, it is not included in \mathcal{R}. We can make this more explicit. 
Thanks for pointing this out.

**Comment by rshaojimmy** [comment]
I see. Thanks so much.
